/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;
import java.rmi.Naming;
import java.rmi.*;
import java.net.MalformedURLException;
import java.io.*;
import java.awt.*;
import javax.swing.JTextField;
import javax.swing.JOptionPane;
import database_table.Employee;
import shared.rmi_interface;

/**
 *
 * @author Asus
 */
public class frontendGUI extends javax.swing.JFrame {
    
    private CardLayout cardLayout;
    private boolean isShowPassword;    
    private boolean isRemenberMe;
    private boolean isUsernamePlaceholder = true;    
    private boolean isPasswordPlaceholder = true;
    /**
     * Creates new form registrationGUI
     */
    public frontendGUI() {
        initComponents();
        this.cardLayout = (CardLayout) getContentPane().getLayout();
        addPlaceholderStyle(LoginUsernameInput);        
        addPlaceholderStyle(LoginPasswordInput);
        LoginInvalidMsgTitle.setVisible(false);
        LoginInvalidContent.setVisible(false);
        
        File file = new File("user.usr");
        if (file.exists()) { // Check if the file exists
            try {
                ObjectInputStream in = new ObjectInputStream(new FileInputStream("user.usr"));
                LoginUsernameInput.setText((String) in.readObject());
                removePlaceholderStyle(LoginUsernameInput);
                in.close();

                LoginRemenberMeCheckBox.setSelected(true);

                if (file.delete()) {
                    System.out.println("File deleted successfully");
                } else {
                    System.out.println("Failed to delete the file");
                }
            } catch (IOException ex) {
                ex.printStackTrace();
            } catch (ClassNotFoundException ex) {
                ex.printStackTrace();
            }
        }else {
            System.out.println("The user crendentials file does not exist.");
        }
    }
    
    public void addPlaceholderStyle(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(Font.ITALIC);
        textField.setFont(font);
        textField.setForeground(Color.gray);
    }
    
    public void removePlaceholderStyle(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(Font.PLAIN|Font.BOLD);
        textField.setFont(font);
        textField.setForeground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPage = new javax.swing.JPanel();
        LoginButton = new javax.swing.JButton();
        LoginUsernameInput = new javax.swing.JTextField();
        LoginUsernameLabel = new javax.swing.JLabel();
        LoginPasswordLabel = new javax.swing.JLabel();
        LoginShowPasswordCheckBox = new javax.swing.JCheckBox();
        LoginPasswordInput = new javax.swing.JPasswordField();
        LoginInvalidMsgTitle = new javax.swing.JLabel();
        LoginInvalidContent = new javax.swing.JLabel();
        LoginRemenberMeCheckBox = new javax.swing.JCheckBox();
        EmployeeLoginLabel = new javax.swing.JLabel();
        firstpage = new javax.swing.JPanel();
        employeeregistrationLabelf = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        retypepasswordLabel = new javax.swing.JLabel();
        readusername = new javax.swing.JTextField();
        readretypepassword = new javax.swing.JPasswordField();
        readpassword = new javax.swing.JPasswordField();
        usernameNote = new javax.swing.JLabel();
        passwordNote = new javax.swing.JLabel();
        retypepasswordvisible = new javax.swing.JCheckBox();
        passwordvisible = new javax.swing.JCheckBox();
        nextpagebutton = new javax.swing.JButton();
        retypepasswordNote = new javax.swing.JLabel();
        invalidinputNote = new javax.swing.JLabel();
        backbutton1 = new javax.swing.JButton();
        secondpage = new javax.swing.JPanel();
        departmentLabel = new javax.swing.JLabel();
        icLabel = new javax.swing.JLabel();
        contactnoLabel = new javax.swing.JLabel();
        fullnameLabel = new javax.swing.JLabel();
        employeeregistrationLabels = new javax.swing.JLabel();
        readfullname = new javax.swing.JTextField();
        readIC = new javax.swing.JTextField();
        icNote = new javax.swing.JLabel();
        contactNote = new javax.swing.JLabel();
        readcontactnumber = new javax.swing.JTextField();
        departmentdropdown = new javax.swing.JComboBox<>();
        fullnameNote = new javax.swing.JLabel();
        nextpagebutton2 = new javax.swing.JButton();
        invalidinputNote2 = new javax.swing.JLabel();
        backbutton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(750, 450));
        getContentPane().setLayout(new java.awt.CardLayout());

        LoginButton.setText("Login");
        LoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtongotoPayRollPage(evt);
            }
        });
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        LoginUsernameInput.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LoginUsernameInput.setText("Username");
        LoginUsernameInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LoginUsernameInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                LoginUsernameInputFocusLost(evt);
            }
        });

        LoginUsernameLabel.setText("Username");

        LoginPasswordLabel.setText("Password");

        LoginShowPasswordCheckBox.setText("Show Password");
        LoginShowPasswordCheckBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginShowPasswordCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                LoginLoginShowPasswordCheckBoxStateChanged(evt);
            }
        });

        LoginPasswordInput.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LoginPasswordInput.setText("Password");
        LoginPasswordInput.setEchoChar('\u0000');
        LoginPasswordInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LoginPasswordInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                LoginPasswordInputFocusLost(evt);
            }
        });

        LoginInvalidMsgTitle.setForeground(new java.awt.Color(255, 0, 0));
        LoginInvalidMsgTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginInvalidMsgTitle.setText("Wrong Credentials");

        LoginInvalidContent.setForeground(new java.awt.Color(255, 51, 51));
        LoginInvalidContent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginInvalidContent.setText("Invalid Username or Password");

        LoginRemenberMeCheckBox.setText("Remember Me");
        LoginRemenberMeCheckBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginRemenberMeCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                LoginRemenberMeCheckBoxStateChanged(evt);
            }
        });

        EmployeeLoginLabel.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        EmployeeLoginLabel.setText("Employee Login ");

        javax.swing.GroupLayout LoginPageLayout = new javax.swing.GroupLayout(LoginPage);
        LoginPage.setLayout(LoginPageLayout);
        LoginPageLayout.setHorizontalGroup(
            LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPageLayout.createSequentialGroup()
                .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPageLayout.createSequentialGroup()
                        .addContainerGap(319, Short.MAX_VALUE)
                        .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LoginShowPasswordCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LoginInvalidContent, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPageLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LoginInvalidMsgTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(LoginPageLayout.createSequentialGroup()
                                    .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(LoginPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LoginUsernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                                    .addGap(84, 84, 84)
                                    .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LoginUsernameInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LoginPasswordInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(LoginPageLayout.createSequentialGroup()
                                            .addGap(3, 3, 3)
                                            .addComponent(LoginRemenberMeCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(306, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPageLayout.createSequentialGroup()
                .addGap(0, 368, Short.MAX_VALUE)
                .addComponent(EmployeeLoginLabel)
                .addGap(350, 350, 350))
        );
        LoginPageLayout.setVerticalGroup(
            LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPageLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(EmployeeLoginLabel)
                .addGap(38, 38, 38)
                .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginUsernameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoginUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(LoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(LoginPageLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(LoginPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPageLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LoginRemenberMeCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LoginPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(LoginShowPasswordCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoginInvalidMsgTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoginInvalidContent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        getContentPane().add(LoginPage, "login");

        firstpage.setPreferredSize(new java.awt.Dimension(750, 450));

        employeeregistrationLabelf.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        employeeregistrationLabelf.setText("Employee Registration ");

        passwordLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        passwordLabel.setText("Password");

        usernameLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        usernameLabel.setText("User Name");

        retypepasswordLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        retypepasswordLabel.setText("Retype Password");

        readusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readusernameActionPerformed(evt);
            }
        });
        readusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                readusernameKeyReleased(evt);
            }
        });

        readretypepassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readretypepasswordActionPerformed(evt);
            }
        });
        readretypepassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                readretypepasswordKeyReleased(evt);
            }
        });

        readpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readpasswordActionPerformed(evt);
            }
        });
        readpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                readpasswordKeyReleased(evt);
            }
        });

        usernameNote.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        usernameNote.setPreferredSize(new java.awt.Dimension(64, 22));

        passwordNote.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        retypepasswordvisible.setText("show");
        retypepasswordvisible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retypepasswordvisibleActionPerformed(evt);
            }
        });

        passwordvisible.setText("show");
        passwordvisible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordvisibleActionPerformed(evt);
            }
        });

        nextpagebutton.setText("Next");
        nextpagebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextpagebuttonMouseClicked(evt);
            }
        });
        nextpagebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextpagebuttonActionPerformed(evt);
            }
        });

        retypepasswordNote.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        backbutton1.setText("Back");
        backbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbutton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout firstpageLayout = new javax.swing.GroupLayout(firstpage);
        firstpage.setLayout(firstpageLayout);
        firstpageLayout.setHorizontalGroup(
            firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstpageLayout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(employeeregistrationLabelf)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstpageLayout.createSequentialGroup()
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(firstpageLayout.createSequentialGroup()
                            .addGap(92, 92, 92)
                            .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(usernameLabel)
                                .addComponent(readusername, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstpageLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(usernameNote, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(firstpageLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(backbutton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(retypepasswordNote, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(retypepasswordLabel)
                        .addComponent(passwordLabel)
                        .addComponent(readretypepassword, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                        .addComponent(readpassword)
                        .addComponent(passwordNote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(28, 28, 28)
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstpageLayout.createSequentialGroup()
                        .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(retypepasswordvisible, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordvisible, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstpageLayout.createSequentialGroup()
                        .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(invalidinputNote, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nextpagebutton))
                        .addContainerGap())))
        );
        firstpageLayout.setVerticalGroup(
            firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstpageLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(employeeregistrationLabelf)
                .addGap(78, 78, 78)
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstpageLayout.createSequentialGroup()
                        .addComponent(usernameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(readusername, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usernameNote, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(firstpageLayout.createSequentialGroup()
                        .addComponent(passwordLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(readpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordvisible))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordNote, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addComponent(retypepasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(readretypepassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retypepasswordvisible))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstpageLayout.createSequentialGroup()
                        .addComponent(invalidinputNote, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(firstpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nextpagebutton)
                            .addComponent(backbutton1))
                        .addGap(20, 20, 20))
                    .addGroup(firstpageLayout.createSequentialGroup()
                        .addComponent(retypepasswordNote, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getContentPane().add(firstpage, "register1");

        secondpage.setPreferredSize(new java.awt.Dimension(750, 450));

        departmentLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        departmentLabel.setText("Department ");

        icLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        icLabel.setText("IC ");

        contactnoLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        contactnoLabel.setText("Contact Number ");

        fullnameLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        fullnameLabel.setText("Full Name");

        employeeregistrationLabels.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        employeeregistrationLabels.setText("Employee Registration ");

        readIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readICActionPerformed(evt);
            }
        });
        readIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                readICKeyReleased(evt);
            }
        });

        icNote.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        contactNote.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        readcontactnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                readcontactnumberKeyReleased(evt);
            }
        });

        departmentdropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Finance", "Developer", "Manager", "Human Resource" }));
        departmentdropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentdropdownActionPerformed(evt);
            }
        });

        nextpagebutton2.setText("Register");
        nextpagebutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextpagebutton2ActionPerformed(evt);
            }
        });

        backbutton2.setText("Back");
        backbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbutton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout secondpageLayout = new javax.swing.GroupLayout(secondpage);
        secondpage.setLayout(secondpageLayout);
        secondpageLayout.setHorizontalGroup(
            secondpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondpageLayout.createSequentialGroup()
                .addGroup(secondpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, secondpageLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(secondpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fullnameLabel)
                            .addComponent(icLabel)
                            .addComponent(readfullname, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fullnameNote, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(readIC, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(icNote, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addGroup(secondpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(departmentLabel)
                            .addComponent(contactnoLabel)
                            .addComponent(readcontactnumber)
                            .addComponent(departmentdropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contactNote, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, secondpageLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(employeeregistrationLabels))
                    .addGroup(secondpageLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(backbutton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(secondpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(invalidinputNote2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nextpagebutton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(17, 17, 17))
        );
        secondpageLayout.setVerticalGroup(
            secondpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondpageLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(employeeregistrationLabels)
                .addGap(33, 33, 33)
                .addGroup(secondpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(secondpageLayout.createSequentialGroup()
                        .addComponent(fullnameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(readfullname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(fullnameNote, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(icLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(readIC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(secondpageLayout.createSequentialGroup()
                        .addComponent(departmentLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(departmentdropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(contactnoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(readcontactnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(secondpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contactNote, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icNote, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(invalidinputNote2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(secondpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextpagebutton2)
                    .addComponent(backbutton2))
                .addGap(32, 32, 32))
        );

        getContentPane().add(secondpage, "register2");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private static rmi_interface Obj;
    
    private static rmi_interface getRMIObject() {
        if (Obj == null) { 
            try {
                Obj = (rmi_interface) Naming.lookup("rmi://localhost:5000/AutomatedPayrollSystem");
            } catch (NotBoundException | MalformedURLException | RemoteException ex) {
                ex.printStackTrace();
                Obj = null;
            }
        }
        
        return Obj;
    }
    
    private void readusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_readusernameActionPerformed

    private void readretypepasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readretypepasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_readretypepasswordActionPerformed

    private void readpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_readpasswordActionPerformed

    private void retypepasswordvisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retypepasswordvisibleActionPerformed
        // TODO add your handling code here:
        if (retypepasswordvisible.isSelected()) {
            readretypepassword.setEchoChar((char) 0); 
        } else {
            readretypepassword.setEchoChar('*'); 
        }
    }//GEN-LAST:event_retypepasswordvisibleActionPerformed

    private void passwordvisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordvisibleActionPerformed
        // TODO add your handling code here:
        if (passwordvisible.isSelected()) {
            readpassword.setEchoChar((char) 0); 
        } else {
            readpassword.setEchoChar('*'); 
        }
    }//GEN-LAST:event_passwordvisibleActionPerformed

    private void nextpagebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextpagebuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextpagebuttonActionPerformed

    private void departmentdropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentdropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentdropdownActionPerformed

    private void nextpagebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextpagebuttonMouseClicked
        // TODO add your handling code here:
        String userName = readusername.getText();
        boolean uEmpty = userName.isEmpty();
        String feedback1 = isValidUsername(userName);
        boolean validusername = false;
        if (!uEmpty){
            validusername = feedback1.equals("Valid");
        }
        
        String passWord = new String(readpassword.getPassword());
        boolean pEmpty = passWord.isEmpty();
        String feedback2 = isValidPassword(passWord);
        boolean validpassword = feedback2.equals("Valid");
        
        String retypePassWord = new String(readretypepassword.getPassword());
        boolean rEmpty = retypePassWord.isEmpty();
        String feedback3 = isValidRetypePassword(passWord, retypePassWord);
        boolean validretypepassword = feedback3.equals("Valid");
        
        if (uEmpty || pEmpty || rEmpty){
            JOptionPane.showMessageDialog(rootPane, "The Input Field can't be Empty");
        }
        
        if (validusername && validpassword && validretypepassword){
            this.cardLayout.show(getContentPane(), "register2");
        }else{
            this.cardLayout.show(getContentPane(), "register1");
            invalidinputNote.setVisible(true);
            invalidinputNote.setText("<html>Invalid Input</html>");
        }
    }//GEN-LAST:event_nextpagebuttonMouseClicked

    private void readpasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_readpasswordKeyReleased
        // TODO add your handling code here:
        
        String passWord = new String(readpassword.getPassword());
        String feedback = isValidPassword(passWord);
        
        if (!"Valid".equals(feedback)) {
            passwordNote.setText(feedback); 
            passwordNote.setVisible(true);  
        } else {
            passwordNote.setVisible(false);
        }
    }//GEN-LAST:event_readpasswordKeyReleased

    private void readusernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_readusernameKeyReleased
        // TODO add your handling code here:
        String userName = readusername.getText();
        String feedback = isValidUsername(userName);
        
        if (!"Valid".equals(feedback)) {
            usernameNote.setText(feedback); 
            usernameNote.setVisible(true);  
        } else {
            usernameNote.setVisible(false);
        }
    }//GEN-LAST:event_readusernameKeyReleased

    private void readretypepasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_readretypepasswordKeyReleased
        // TODO add your handling code here:
        String passWord = new String(readpassword.getPassword());
        String retypePassWord = new String(readretypepassword.getPassword());
        String feedback = isValidRetypePassword(passWord, retypePassWord);
        
        if (!"Valid".equals(feedback)) {
            retypepasswordNote.setText(feedback); 
            retypepasswordNote.setVisible(true); 
        } else {
            retypepasswordNote.setVisible(false);
        }
    }//GEN-LAST:event_readretypepasswordKeyReleased

    private void readICKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_readICKeyReleased
        // TODO add your handling code here:
        String IC = readIC.getText();
        String feedback = isValidIC(IC);
        
        if (!"Valid".equals(feedback)) {
            icNote.setText(feedback); 
            icNote.setVisible(true); 
        } else {
            icNote.setVisible(false);
        } 
        
    }//GEN-LAST:event_readICKeyReleased

    private void readcontactnumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_readcontactnumberKeyReleased
        // TODO add your handling code here:
        String contact = readcontactnumber.getText();
        String feedback = isValidContact(contact);
        
        if (!"Valid".equals(feedback)) {
            contactNote.setText(feedback); 
            contactNote.setVisible(true); 
        } else {
            contactNote.setVisible(false);
        } 
    }//GEN-LAST:event_readcontactnumberKeyReleased

    private void nextpagebutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextpagebutton2ActionPerformed
        // TODO add your handling code here:
        String fullname = readfullname.getText();
        boolean fEmpty = fullname.isEmpty();
        boolean validfullname = false;
        
        String ic = readIC.getText();
        boolean iEmpty = ic.isEmpty();
        String feedback1 = "";
        boolean validic;
        
        
        String contact = readcontactnumber.getText();
        boolean cEmpty = contact.isEmpty();
        String feedback2 = "";
        boolean validcontact;
        
        if (!fEmpty){
            validfullname = true;
        }
        
        if (!iEmpty){
            feedback1 = isValidIC(ic);
        }
        
        if (!cEmpty){
            feedback2 = isValidContact(contact);
        }
        
        validic = feedback1.equals("Valid");
        validcontact = feedback2.equals("Valid");
        
        if (fEmpty || iEmpty || cEmpty){
            JOptionPane.showMessageDialog(rootPane, "The Input Field can't be Empty");
        }
        
        Employee employee = new Employee();
        
        if (validfullname && validic && validcontact){
            employee.setUsername(readusername.getText());
            employee.setPassword(new String(readpassword.getPassword()));
            employee.setFullName(fullname);
            employee.setICNO(ic);
            employee.setDepartment((String)departmentdropdown.getSelectedItem());
            employee.setContactNO(contact);
            
            String response = sendUserData(employee);
            if (response.equals("Success")){
                JOptionPane.showMessageDialog(rootPane, "User registered successfully!");
                this.cardLayout.show(getContentPane(), "login");
                invalidinputNote2.setVisible(false);
            } else{
                JOptionPane.showMessageDialog(rootPane, response);
                this.cardLayout.show(getContentPane(), "register1");
            }
        }else{
            this.cardLayout.show(getContentPane(), "register2");
            invalidinputNote2.setVisible(true);
            invalidinputNote2.setText("<html>Invalid Input</html>");
        }
        
        
    }//GEN-LAST:event_nextpagebutton2ActionPerformed

    private void backbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbutton2ActionPerformed
        // TODO add your handling code here:
        this.cardLayout.show(getContentPane(), "register1");
    }//GEN-LAST:event_backbutton2ActionPerformed

    private void backbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbutton1ActionPerformed
        // TODO add your handling code here:
        this.cardLayout.show(getContentPane(), "login");
    }//GEN-LAST:event_backbutton1ActionPerformed

    private void LoginButtongotoPayRollPage(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtongotoPayRollPage
        // TODO add your handling code here:
        rmi_interface Obj = getRMIObject();
        
        try {
            char[] passwordChars = LoginPasswordInput.getPassword();
            String password = new String(passwordChars);
            if(Obj.Login(LoginUsernameInput.getText(), password)){
                if(isRemenberMe){
                    String LoginUsername = LoginUsernameInput.getText();
                    FileOutputStream fout = new FileOutputStream("user.usr");
                    ObjectOutputStream out = new ObjectOutputStream(fout);
                    out.writeObject(LoginUsername);
                    out.flush();
                    out.close();
                }
                this.cardLayout.show(getContentPane(), "card2");
            }else{
                LoginInvalidMsgTitle.setVisible(true);
                LoginInvalidContent.setVisible(true);
            }
        } catch (RemoteException ex) {
            ex.printStackTrace();
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_LoginButtongotoPayRollPage

    private void LoginUsernameInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LoginUsernameInputFocusGained
        // TODO add your handling code here:
        if(LoginUsernameInput.getText().equals("Username") && isUsernamePlaceholder){
            LoginUsernameInput.setText(null);
            LoginUsernameInput.requestFocus();
            removePlaceholderStyle(LoginUsernameInput);
            isUsernamePlaceholder = false;
        }
    }//GEN-LAST:event_LoginUsernameInputFocusGained

    private void LoginUsernameInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LoginUsernameInputFocusLost
        // TODO add your handling code here:
        if(LoginUsernameInput.getText().length() == 0){
            LoginUsernameInput.setText("Username");
            addPlaceholderStyle(LoginUsernameInput);
            isUsernamePlaceholder = true;
        }
    }//GEN-LAST:event_LoginUsernameInputFocusLost

    private void LoginLoginShowPasswordCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_LoginLoginShowPasswordCheckBoxStateChanged
        // TODO add your handling code here:
        isShowPassword = LoginShowPasswordCheckBox.isSelected();
        char[] passwordChars = LoginPasswordInput.getPassword();
        String password = new String(passwordChars);
        if(isShowPassword){
            LoginPasswordInput.setEchoChar('\u0000');
        }
        else if(password.length() > 0 && !isPasswordPlaceholder){
            LoginPasswordInput.setEchoChar('●');
        }
    }//GEN-LAST:event_LoginLoginShowPasswordCheckBoxStateChanged

    private void LoginPasswordInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LoginPasswordInputFocusGained
        // TODO add your handling code here:
        char[] passwordChars = LoginPasswordInput.getPassword();
        String password = new String(passwordChars);
        if(password.equals("Password") && isPasswordPlaceholder){
            LoginPasswordInput.setText(null);
            LoginPasswordInput.requestFocus();
            if(!this.isShowPassword){
                LoginPasswordInput.setEchoChar('●');
            }
            removePlaceholderStyle(LoginPasswordInput);
            isPasswordPlaceholder = false;
        }
    }//GEN-LAST:event_LoginPasswordInputFocusGained

    private void LoginPasswordInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LoginPasswordInputFocusLost
        // TODO add your handling code here:
        char[] passwordChars = LoginPasswordInput.getPassword();
        String password = new String(passwordChars);
        if(password.length() == 0){
            LoginPasswordInput.setText("Password");
            LoginPasswordInput.setEchoChar('\u0000');
            addPlaceholderStyle(LoginPasswordInput);
            isPasswordPlaceholder = true;
        }
    }//GEN-LAST:event_LoginPasswordInputFocusLost

    private void LoginRemenberMeCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_LoginRemenberMeCheckBoxStateChanged
        // TODO add your handling code here:
        isRemenberMe = LoginRemenberMeCheckBox.isSelected();
    }//GEN-LAST:event_LoginRemenberMeCheckBoxStateChanged

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void readICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_readICActionPerformed
    
    private static String isValidContact (String contactno){
        StringBuilder feedback = new StringBuilder("<html>Invalid Contact Number: <br>");
        
        if (!contactno.matches("\\d+")){
            feedback.append("* Contact number should be a 12-digit number");
        }else{
            return "Valid";
        }
        
        feedback.append("</html>");
        return feedback.toString();
    }
    
    private static String isValidIC (String ic){
        
        StringBuilder feedback = new StringBuilder("<html>Invalid IC: <br>");
        
        if (!ic.matches("\\d{12}")){
            feedback.append("* IC number should be a 12-digit number");
        }else{
            return "Valid";
        }
        
        feedback.append("</html>");
        return feedback.toString();
    }
    
    private static String isValidRetypePassword (String password, String retypepassword){
        
        boolean correct = retypepassword.equals(password);
        StringBuilder feedback = new StringBuilder("<html>Invalid Retype Password: <br>");
        
        if (!correct) {
            feedback.append("* Retype Password different with Password");
        }else{
            return "Valid";
        }
        
        feedback.append("</html>");
        return feedback.toString();
    }
    
    private static String sendUserData(Employee employee){
        rmi_interface Obj = getRMIObject();
        try {
            String response = Obj.registrationRequest(employee);
            return response;
        } catch (Exception e) {
            e.printStackTrace();
            return "Error: Unable to connect to the server.";
        }
    }
    
    private static String isValidUsername (String username){
        boolean hasSpecial = username.matches(".*[!@#$%^&*(),.?\":{}|<>].*");
        boolean isUnique;
        StringBuilder feedback = new StringBuilder("<html>Invalid Username: <br>");
        rmi_interface Obj = getRMIObject();
        String response = "";
        
        if (hasSpecial) {
            feedback.append("* User Name shouldn't contain a special symbol");
        }
        
        try{
            response = Obj.uniqueName(username);
        } catch (Exception e){
            e.printStackTrace();
        }
        
        isUnique = response.equals("Unique");
        
        if (!isUnique){
            feedback.append("* User Name existing in system, user name should be unique");
        }
        
        if (isUnique && !hasSpecial){
            return "Valid";
        }

        feedback.append("</html>");
        return feedback.toString();
    }
    
    private static String isValidPassword(String password){
        boolean hasUpper = password.matches(".*[A-Z].*");
        boolean hasLower = password.matches(".*[a-z].*");
        boolean hasSpecial = password.matches(".*[!@#$%^&*(),.?\":{}|<>].*");
        boolean hasNumber = password.matches(".*[0-9].*");
        boolean hasSpace = password.matches(" ");
        
        StringBuilder feedback = new StringBuilder("<html>Invalid Password: <br>");
        if (!hasUpper) {
            feedback.append("* At least one uppercase letter<br>");
        }
        if (!hasLower) {
            feedback.append("* At least one lowercase letter<br>");
        }
        if (!hasSpecial) {
            feedback.append("* At least one special symbol<br>");
        }
        if (!hasNumber) {
            feedback.append("* At least one number<br>");
        }
        if (hasSpace) {
            feedback.append("* Password can't contain space<br>");
        }

        if (hasUpper && hasLower && hasSpecial && hasNumber) {
            
            return "Valid";
        }

        feedback.append("</html>");
        return feedback.toString();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frontendGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frontendGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frontendGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frontendGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frontendGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmployeeLoginLabel;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel LoginInvalidContent;
    private javax.swing.JLabel LoginInvalidMsgTitle;
    private javax.swing.JPanel LoginPage;
    private javax.swing.JPasswordField LoginPasswordInput;
    private javax.swing.JLabel LoginPasswordLabel;
    private javax.swing.JCheckBox LoginRemenberMeCheckBox;
    private javax.swing.JCheckBox LoginShowPasswordCheckBox;
    private javax.swing.JTextField LoginUsernameInput;
    private javax.swing.JLabel LoginUsernameLabel;
    private javax.swing.JButton backbutton1;
    private javax.swing.JButton backbutton2;
    private javax.swing.JLabel contactNote;
    private javax.swing.JLabel contactnoLabel;
    private javax.swing.JLabel departmentLabel;
    private javax.swing.JComboBox<String> departmentdropdown;
    private javax.swing.JLabel employeeregistrationLabelf;
    private javax.swing.JLabel employeeregistrationLabels;
    private javax.swing.JPanel firstpage;
    private javax.swing.JLabel fullnameLabel;
    private javax.swing.JLabel fullnameNote;
    private javax.swing.JLabel icLabel;
    private javax.swing.JLabel icNote;
    private javax.swing.JLabel invalidinputNote;
    private javax.swing.JLabel invalidinputNote2;
    private javax.swing.JButton nextpagebutton;
    private javax.swing.JButton nextpagebutton2;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel passwordNote;
    private javax.swing.JCheckBox passwordvisible;
    private javax.swing.JTextField readIC;
    private javax.swing.JTextField readcontactnumber;
    private javax.swing.JTextField readfullname;
    private javax.swing.JPasswordField readpassword;
    private javax.swing.JPasswordField readretypepassword;
    private javax.swing.JTextField readusername;
    private javax.swing.JLabel retypepasswordLabel;
    private javax.swing.JLabel retypepasswordNote;
    private javax.swing.JCheckBox retypepasswordvisible;
    private javax.swing.JPanel secondpage;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel usernameNote;
    // End of variables declaration//GEN-END:variables
}
