/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.Date;
import java.time.LocalDate;
import backend.Deduction;
import backend.Employee;
import backend.Payroll;
import backend.SalaryDetail;
import backend.SalaryHistory;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author wjing
 */
public class payrollGUI extends javax.swing.JFrame {
    /**
     * Creates new form payrollGUI
     */
    private LocalDate ld = LocalDate.now();
    private Date current_date = Date.valueOf(ld);
    private Date selected_date = Date.valueOf(ld);
    private Date hr_selected_date = Date.valueOf(ld);
    
    public payrollGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        mrg_panel = new javax.swing.JPanel();
        mrg_view_button = new javax.swing.JButton();
        mrg_yr_tf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        mrg_month_cb = new javax.swing.JComboBox<>();
        personal_details_panel = new javax.swing.JPanel();
        personal_details_label = new javax.swing.JLabel();
        personal_name_label = new javax.swing.JLabel();
        personal_ic_textfield = new javax.swing.JTextField();
        ic_no_label = new javax.swing.JLabel();
        contact_no_label = new javax.swing.JLabel();
        personal_name_textfield = new javax.swing.JTextField();
        personal_contact_textfield = new javax.swing.JTextField();
        department_label = new javax.swing.JLabel();
        personal_department_textfield = new javax.swing.JTextField();
        pd_salary_button = new javax.swing.JButton();
        pd_back_button = new javax.swing.JButton();
        salary_details_panel = new javax.swing.JPanel();
        month_combo_box = new javax.swing.JComboBox<>();
        year_combo_box = new javax.swing.JComboBox<>();
        salary_name_label = new javax.swing.JLabel();
        base_salary_label = new javax.swing.JLabel();
        hourly_rate_label = new javax.swing.JLabel();
        working_hours_label = new javax.swing.JLabel();
        allowance_label = new javax.swing.JLabel();
        overtime_hour_label = new javax.swing.JLabel();
        salary_name_textfield = new javax.swing.JTextField();
        base_salary_textfield = new javax.swing.JTextField();
        hourly_rate_textfield = new javax.swing.JTextField();
        working_hours_textfield = new javax.swing.JTextField();
        allowance_textfield = new javax.swing.JTextField();
        overtime_hours_textfield = new javax.swing.JTextField();
        gross_salary_label = new javax.swing.JLabel();
        gross_salary_textfield = new javax.swing.JTextField();
        epf_label = new javax.swing.JLabel();
        socso_label = new javax.swing.JLabel();
        eis_label = new javax.swing.JLabel();
        income_tax_label = new javax.swing.JLabel();
        leave_deduction_label = new javax.swing.JLabel();
        additional_deduction_label = new javax.swing.JLabel();
        additional_deduction_textfield = new javax.swing.JTextField();
        epf_textfield = new javax.swing.JTextField();
        socso_textfield = new javax.swing.JTextField();
        eis_textfield = new javax.swing.JTextField();
        income_tax_textfield = new javax.swing.JTextField();
        leave_deduction_textfield = new javax.swing.JTextField();
        nnet_dalary_label = new javax.swing.JLabel();
        net_salary_textfield = new javax.swing.JTextField();
        salary_back_button = new javax.swing.JButton();
        view_reason_button = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        monthly_report = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mr_tb = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mr_date_tf = new javax.swing.JTextField();
        mr_no_emp_tf = new javax.swing.JTextField();
        mr_view_back_button = new javax.swing.JButton();
        total_table = new javax.swing.JTable();
        hr_panel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        go_bsd_button = new javax.swing.JButton();
        go_ms_button = new javax.swing.JButton();
        hr_back_login_button = new javax.swing.JButton();
        go_mr_button = new javax.swing.JButton();
        bsd_update_panel = new javax.swing.JPanel();
        bsd_hr_tf = new javax.swing.JTextField();
        bsd_empid_tf = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        bsd_bs_tf = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        bsd_wh_tf = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        bsd_confirm_button = new javax.swing.JButton();
        bsd_return_button = new javax.swing.JButton();
        ms_update_panel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ms_empid_tf = new javax.swing.JTextField();
        ms_ot_tf = new javax.swing.JTextField();
        ms_allowance_tf = new javax.swing.JTextField();
        ms_ld_tf = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        ms_confirm_button = new javax.swing.JButton();
        ms_return_button = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        ms_ad_tf = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        ms_reason_tf = new javax.swing.JTextField();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        mrg_view_button.setText("View");
        mrg_view_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrg_view_buttonActionPerformed(evt);
            }
        });

        mrg_yr_tf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mrg_yr_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrg_yr_tfActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Month:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Year:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Select year and month to generate report:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setText("Monthly Report");

        mrg_month_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        mrg_month_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrg_month_cbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mrg_panelLayout = new javax.swing.GroupLayout(mrg_panel);
        mrg_panel.setLayout(mrg_panelLayout);
        mrg_panelLayout.setHorizontalGroup(
            mrg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mrg_panelLayout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addGroup(mrg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mrg_panelLayout.createSequentialGroup()
                        .addGroup(mrg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(34, 34, 34)
                        .addGroup(mrg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mrg_month_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mrg_yr_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mrg_panelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 376, Short.MAX_VALUE))))
            .addGroup(mrg_panelLayout.createSequentialGroup()
                .addGroup(mrg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mrg_panelLayout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(jLabel8))
                    .addGroup(mrg_panelLayout.createSequentialGroup()
                        .addGap(408, 408, 408)
                        .addComponent(mrg_view_button, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mrg_panelLayout.setVerticalGroup(
            mrg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mrg_panelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel8)
                .addGap(51, 51, 51)
                .addComponent(jLabel7)
                .addGap(40, 40, 40)
                .addGroup(mrg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(mrg_yr_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(mrg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(mrg_month_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(mrg_view_button, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );

        getContentPane().add(mrg_panel, "card5");

        personal_details_label.setFont(new java.awt.Font("Noto Sans", 1, 36)); // NOI18N
        personal_details_label.setText("Personal Details");

        personal_name_label.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        personal_name_label.setText("Name:");

        personal_ic_textfield.setEditable(false);
        personal_ic_textfield.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N

        ic_no_label.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        ic_no_label.setText("IC No.:");

        contact_no_label.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        contact_no_label.setText("Contact No.:");

        personal_name_textfield.setEditable(false);
        personal_name_textfield.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        personal_name_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personal_name_textfieldActionPerformed(evt);
            }
        });

        personal_contact_textfield.setEditable(false);
        personal_contact_textfield.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N

        department_label.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        department_label.setText("Department:");

        personal_department_textfield.setEditable(false);
        personal_department_textfield.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N

        pd_salary_button.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        pd_salary_button.setText("View Payslip");
        pd_salary_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pd_salary_buttonMouseClicked(evt);
            }
        });
        pd_salary_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_salary_buttonActionPerformed(evt);
            }
        });

        pd_back_button.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        pd_back_button.setText("<Back");
        pd_back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pd_back_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout personal_details_panelLayout = new javax.swing.GroupLayout(personal_details_panel);
        personal_details_panel.setLayout(personal_details_panelLayout);
        personal_details_panelLayout.setHorizontalGroup(
            personal_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personal_details_panelLayout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addGroup(personal_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(personal_details_label)
                    .addComponent(department_label)
                    .addComponent(contact_no_label)
                    .addGroup(personal_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(personal_name_label)
                        .addComponent(ic_no_label)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personal_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(personal_department_textfield, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personal_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(personal_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(personal_ic_textfield)
                        .addComponent(personal_contact_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(89, 89, 89)
                .addComponent(pd_salary_button)
                .addGap(66, 66, 66))
            .addGroup(personal_details_panelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(pd_back_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        personal_details_panelLayout.setVerticalGroup(
            personal_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personal_details_panelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(personal_details_label)
                .addGap(39, 39, 39)
                .addGroup(personal_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personal_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personal_name_label)
                    .addComponent(pd_salary_button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personal_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personal_ic_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ic_no_label))
                .addGap(18, 18, 18)
                .addGroup(personal_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personal_contact_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contact_no_label))
                .addGap(18, 18, 18)
                .addGroup(personal_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(department_label)
                    .addComponent(personal_department_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(pd_back_button)
                .addGap(38, 38, 38))
        );

        getContentPane().add(personal_details_panel, "personal_details_card");

        month_combo_box.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        month_combo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        month_combo_box.setToolTipText("Select Month");
        month_combo_box.setName(""); // NOI18N
        month_combo_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                month_combo_boxActionPerformed(evt);
            }
        });

        year_combo_box.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        year_combo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034" }));
        year_combo_box.setToolTipText("Select Year");
        year_combo_box.setName(""); // NOI18N
        year_combo_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year_combo_boxActionPerformed(evt);
            }
        });

        salary_name_label.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        salary_name_label.setText("Name:");

        base_salary_label.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        base_salary_label.setText("Base Salary:");

        hourly_rate_label.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        hourly_rate_label.setText("Hourly Rate:");

        working_hours_label.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        working_hours_label.setText("Working Hours:");

        allowance_label.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        allowance_label.setText("Allowance:");

        overtime_hour_label.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        overtime_hour_label.setText("Overtime Hours:");

        salary_name_textfield.setEditable(false);
        salary_name_textfield.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        salary_name_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salary_name_textfieldActionPerformed(evt);
            }
        });

        base_salary_textfield.setEditable(false);
        base_salary_textfield.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        base_salary_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                base_salary_textfieldActionPerformed(evt);
            }
        });

        hourly_rate_textfield.setEditable(false);
        hourly_rate_textfield.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N

        working_hours_textfield.setEditable(false);
        working_hours_textfield.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N

        allowance_textfield.setEditable(false);
        allowance_textfield.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N

        overtime_hours_textfield.setEditable(false);
        overtime_hours_textfield.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N

        gross_salary_label.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        gross_salary_label.setText("Gross Salary:");

        gross_salary_textfield.setEditable(false);
        gross_salary_textfield.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N

        epf_label.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        epf_label.setText("EPF:");

        socso_label.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        socso_label.setText("SOCSO:");

        eis_label.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        eis_label.setText("EIS:");

        income_tax_label.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        income_tax_label.setText("Income Tax:");

        leave_deduction_label.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        leave_deduction_label.setText("Leave Deduction:");

        additional_deduction_label.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        additional_deduction_label.setText("Additional Deduction:");

        additional_deduction_textfield.setEditable(false);
        additional_deduction_textfield.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N

        epf_textfield.setEditable(false);
        epf_textfield.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N

        socso_textfield.setEditable(false);
        socso_textfield.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N

        eis_textfield.setEditable(false);
        eis_textfield.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N

        income_tax_textfield.setEditable(false);
        income_tax_textfield.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N

        leave_deduction_textfield.setEditable(false);
        leave_deduction_textfield.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N

        nnet_dalary_label.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        nnet_dalary_label.setText("Month End Salary:");

        net_salary_textfield.setEditable(false);
        net_salary_textfield.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N

        salary_back_button.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        salary_back_button.setText("<Back");
        salary_back_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salary_back_buttonMouseClicked(evt);
            }
        });
        salary_back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salary_back_buttonActionPerformed(evt);
            }
        });

        view_reason_button.setText("Reason");
        view_reason_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_reason_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout salary_details_panelLayout = new javax.swing.GroupLayout(salary_details_panel);
        salary_details_panel.setLayout(salary_details_panelLayout);
        salary_details_panelLayout.setHorizontalGroup(
            salary_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salary_details_panelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(salary_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(salary_back_button)
                    .addGroup(salary_details_panelLayout.createSequentialGroup()
                        .addGroup(salary_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(month_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salary_name_label)
                            .addGroup(salary_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(hourly_rate_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(base_salary_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(working_hours_label)
                            .addComponent(allowance_label)
                            .addComponent(overtime_hour_label)
                            .addComponent(gross_salary_label))
                        .addGap(18, 18, 18)
                        .addGroup(salary_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(year_combo_box, 0, 140, Short.MAX_VALUE)
                            .addComponent(base_salary_textfield)
                            .addComponent(hourly_rate_textfield)
                            .addComponent(working_hours_textfield)
                            .addComponent(allowance_textfield)
                            .addComponent(overtime_hours_textfield)
                            .addComponent(gross_salary_textfield)
                            .addComponent(salary_name_textfield))
                        .addGap(132, 132, 132)
                        .addGroup(salary_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(additional_deduction_label)
                            .addGroup(salary_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(socso_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(epf_label, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(eis_label, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(income_tax_label)
                            .addComponent(leave_deduction_label)
                            .addComponent(nnet_dalary_label))
                        .addGap(86, 86, 86)
                        .addGroup(salary_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(epf_textfield)
                            .addComponent(socso_textfield)
                            .addComponent(eis_textfield)
                            .addComponent(income_tax_textfield)
                            .addComponent(leave_deduction_textfield)
                            .addComponent(additional_deduction_textfield)
                            .addComponent(net_salary_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(view_reason_button))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        salary_details_panelLayout.setVerticalGroup(
            salary_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salary_details_panelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(salary_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(month_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(salary_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(salary_details_panelLayout.createSequentialGroup()
                        .addGroup(salary_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salary_name_label)
                            .addComponent(salary_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(salary_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(base_salary_label)
                            .addComponent(base_salary_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(salary_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hourly_rate_label)
                            .addComponent(hourly_rate_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(salary_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(working_hours_label)
                            .addComponent(working_hours_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(salary_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(allowance_label)
                            .addComponent(allowance_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(salary_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(overtime_hour_label)
                            .addComponent(overtime_hours_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(salary_details_panelLayout.createSequentialGroup()
                        .addGroup(salary_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(epf_label)
                            .addComponent(epf_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(salary_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(socso_label)
                            .addComponent(socso_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(salary_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eis_label)
                            .addComponent(eis_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(salary_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(income_tax_label)
                            .addComponent(income_tax_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(salary_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(leave_deduction_label)
                            .addComponent(leave_deduction_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(salary_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(additional_deduction_label)
                            .addComponent(additional_deduction_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(view_reason_button, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(salary_details_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gross_salary_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gross_salary_label)
                    .addComponent(nnet_dalary_label)
                    .addComponent(net_salary_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(salary_back_button)
                .addGap(19, 19, 19))
        );

        getContentPane().add(salary_details_panel, "salary_details_card");

        mr_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Emp No.", "Employee name", "Basic Pay", "Gross Pay", "EPF", "Socso", "EIS", "Deduction", "Month End Pay"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        mr_tb.setToolTipText("");
        mr_tb.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(mr_tb);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Monthly Report");

        jLabel1.setText("GRAND TOTAL:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Date:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("No. of Employees:");

        mr_date_tf.setEditable(false);
        mr_date_tf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mr_date_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mr_date_tfActionPerformed(evt);
            }
        });

        mr_no_emp_tf.setEditable(false);
        mr_no_emp_tf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mr_no_emp_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mr_no_emp_tfActionPerformed(evt);
            }
        });

        mr_view_back_button.setText("Back");
        mr_view_back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mr_view_back_buttonActionPerformed(evt);
            }
        });

        total_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Total Basic Pay", "Total Gross Pay", "Total EPF", "Total Socso", "Total EIS", "Total Deduction", "Total Month End Pay"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        total_table.setAutoscrolls(false);

        javax.swing.GroupLayout monthly_reportLayout = new javax.swing.GroupLayout(monthly_report);
        monthly_report.setLayout(monthly_reportLayout);
        monthly_reportLayout.setHorizontalGroup(
            monthly_reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, monthly_reportLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mr_date_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mr_no_emp_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
            .addGroup(monthly_reportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 927, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, monthly_reportLayout.createSequentialGroup()
                .addContainerGap(843, Short.MAX_VALUE)
                .addComponent(mr_view_back_button)
                .addGap(24, 24, 24))
            .addGroup(monthly_reportLayout.createSequentialGroup()
                .addGroup(monthly_reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(monthly_reportLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(monthly_reportLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total_table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        monthly_reportLayout.setVerticalGroup(
            monthly_reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monthly_reportLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(monthly_reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(mr_no_emp_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mr_date_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addGroup(monthly_reportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(total_table, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mr_view_back_button)
                .addGap(19, 19, 19))
        );

        getContentPane().add(monthly_report, "monthly_report");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setText("HR Menu");

        go_bsd_button.setText("Update Employee Basic Salary");
        go_bsd_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go_bsd_buttonActionPerformed(evt);
            }
        });

        go_ms_button.setText("Update Employee Supplementary Pay");
        go_ms_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go_ms_buttonActionPerformed(evt);
            }
        });

        hr_back_login_button.setText("Return to Login");
        hr_back_login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hr_back_login_buttonActionPerformed(evt);
            }
        });

        go_mr_button.setText("View Payroll Monthly Report");
        go_mr_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go_mr_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout hr_panelLayout = new javax.swing.GroupLayout(hr_panel);
        hr_panel.setLayout(hr_panelLayout);
        hr_panelLayout.setHorizontalGroup(
            hr_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hr_panelLayout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .addGroup(hr_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hr_panelLayout.createSequentialGroup()
                        .addGroup(hr_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(go_ms_button, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(go_bsd_button, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(go_mr_button, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(213, 213, 213))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hr_panelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(387, 387, 387))))
            .addGroup(hr_panelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(hr_back_login_button)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        hr_panelLayout.setVerticalGroup(
            hr_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hr_panelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel9)
                .addGap(51, 51, 51)
                .addComponent(go_bsd_button, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(go_ms_button, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(go_mr_button, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(hr_back_login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        getContentPane().add(hr_panel, "card6");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel19.setText("Base Salary Update");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Fill in the information for fixed salary registration.");

        jLabel21.setText("Base Salary:");

        jLabel22.setText("Hourly Rate:");

        jLabel23.setText("Working Hour:");

        jLabel24.setText("Employee ID:");

        bsd_confirm_button.setText("Enter");
        bsd_confirm_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsd_confirm_buttonActionPerformed(evt);
            }
        });

        bsd_return_button.setText("Return");
        bsd_return_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsd_return_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bsd_update_panelLayout = new javax.swing.GroupLayout(bsd_update_panel);
        bsd_update_panel.setLayout(bsd_update_panelLayout);
        bsd_update_panelLayout.setHorizontalGroup(
            bsd_update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bsd_update_panelLayout.createSequentialGroup()
                .addGroup(bsd_update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bsd_update_panelLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(bsd_return_button, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bsd_confirm_button, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bsd_update_panelLayout.createSequentialGroup()
                        .addGroup(bsd_update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bsd_update_panelLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel20))
                            .addGroup(bsd_update_panelLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel19)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                        .addGroup(bsd_update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)
                            .addGroup(bsd_update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bsd_wh_tf)
                                .addComponent(bsd_bs_tf)
                                .addComponent(bsd_empid_tf)
                                .addComponent(bsd_hr_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(110, 110, 110))
        );
        bsd_update_panelLayout.setVerticalGroup(
            bsd_update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bsd_update_panelLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(bsd_update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bsd_update_panelLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel20))
                    .addGroup(bsd_update_panelLayout.createSequentialGroup()
                        .addGroup(bsd_update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel19))
                        .addGap(0, 0, 0)
                        .addComponent(bsd_empid_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)
                        .addGap(1, 1, 1)
                        .addComponent(bsd_bs_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel22)
                        .addGap(3, 3, 3)
                        .addComponent(bsd_hr_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23)))
                .addGap(0, 0, 0)
                .addComponent(bsd_wh_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bsd_update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bsd_confirm_button, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bsd_return_button, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
        );

        getContentPane().add(bsd_update_panel, "card7");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setText("Monthly Salary Update");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Fill in the information for unfixed salary information.");

        ms_empid_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_empid_tfActionPerformed(evt);
            }
        });

        ms_ot_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_ot_tfActionPerformed(evt);
            }
        });

        jLabel15.setText("Employee ID:");

        jLabel16.setText("Allowance:");

        jLabel17.setText("Overtime Hours:");

        jLabel18.setText("Leave Deduction:");

        ms_confirm_button.setText("Enter");
        ms_confirm_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_confirm_buttonActionPerformed(evt);
            }
        });

        ms_return_button.setText("Return");
        ms_return_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_return_buttonActionPerformed(evt);
            }
        });

        jLabel25.setText("Addtional Deduction:");

        jLabel26.setText("Deduction Reason:");

        javax.swing.GroupLayout ms_update_panelLayout = new javax.swing.GroupLayout(ms_update_panel);
        ms_update_panel.setLayout(ms_update_panelLayout);
        ms_update_panelLayout.setHorizontalGroup(
            ms_update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ms_update_panelLayout.createSequentialGroup()
                .addGroup(ms_update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ms_update_panelLayout.createSequentialGroup()
                        .addGroup(ms_update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ms_update_panelLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel14))
                            .addGroup(ms_update_panelLayout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(ms_return_button, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 208, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ms_update_panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel13)))
                .addGap(18, 18, 18)
                .addGroup(ms_update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(ms_update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ms_confirm_button, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(ms_update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(ms_update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ms_ot_tf)
                                .addComponent(ms_allowance_tf)
                                .addComponent(ms_empid_tf)
                                .addComponent(ms_ld_tf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ms_ad_tf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(ms_reason_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(110, 110, 110))
        );
        ms_update_panelLayout.setVerticalGroup(
            ms_update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ms_update_panelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel15)
                .addGap(0, 0, 0)
                .addGroup(ms_update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ms_update_panelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(118, 118, 118)
                        .addComponent(jLabel14))
                    .addGroup(ms_update_panelLayout.createSequentialGroup()
                        .addComponent(ms_empid_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addGap(1, 1, 1)
                        .addComponent(ms_allowance_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ms_ot_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ms_ld_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ms_ad_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ms_reason_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addGroup(ms_update_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ms_confirm_button, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ms_return_button, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
        );

        getContentPane().add(ms_update_panel, "card8");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pd_salary_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pd_salary_buttonMouseClicked
        // TODO add your handling code here:
        personal_details_panel.hide();
        salary_details_panel.show();
    }//GEN-LAST:event_pd_salary_buttonMouseClicked

    private void salary_back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salary_back_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salary_back_buttonActionPerformed

    private void salary_name_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salary_name_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salary_name_textfieldActionPerformed

    private void base_salary_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_base_salary_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_base_salary_textfieldActionPerformed

    private void salary_back_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salary_back_buttonMouseClicked
        // TODO add your handling code here:
        salary_details_panel.hide();
        personal_details_panel.show();
        
    }//GEN-LAST:event_salary_back_buttonMouseClicked

    private void pd_back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_back_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pd_back_buttonActionPerformed

    private void personal_name_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personal_name_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personal_name_textfieldActionPerformed

    private void pd_salary_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pd_salary_buttonActionPerformed
        // TODO add your handling code here:
        
        personal_details_panel.hide();
        salary_details_panel.show();
    }//GEN-LAST:event_pd_salary_buttonActionPerformed

    private void month_combo_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_month_combo_boxActionPerformed
        // TODO add your handling code here:
        String selectedMonth = (String)month_combo_box.getSelectedItem();
        int monthValue = Client.mapMonthToNumber(selectedMonth);
        int yearValue = Integer.parseInt((String) year_combo_box.getSelectedItem());
        LocalDate localdate = LocalDate.of(yearValue,monthValue,1);
        this.selected_date = Date.valueOf(localdate);
        
    }//GEN-LAST:event_month_combo_boxActionPerformed

    private void year_combo_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year_combo_boxActionPerformed
        // TODO add your handling code here:
        String selectedMonth = (String)month_combo_box.getSelectedItem();
        int monthValue = Client.mapMonthToNumber(selectedMonth);
        int yearValue = Integer.parseInt((String) year_combo_box.getSelectedItem());
        LocalDate localdate = LocalDate.of(yearValue,monthValue,1);
        this.selected_date = Date.valueOf(localdate);
        
    }//GEN-LAST:event_year_combo_boxActionPerformed

    private void mr_date_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mr_date_tfActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mr_date_tfActionPerformed

    private void mr_no_emp_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mr_no_emp_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mr_no_emp_tfActionPerformed

    private void mrg_yr_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrg_yr_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mrg_yr_tfActionPerformed

    private void mrg_month_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrg_month_cbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mrg_month_cbActionPerformed

    private void hr_back_login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hr_back_login_buttonActionPerformed
        // TODO add your handling code here:
        hr_panel.hide();
        //show login panel
    }//GEN-LAST:event_hr_back_login_buttonActionPerformed

    private void go_bsd_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go_bsd_buttonActionPerformed
        // TODO add your handling code here:
        hr_panel.hide();
        bsd_update_panel.show();
    }//GEN-LAST:event_go_bsd_buttonActionPerformed

    private void go_ms_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go_ms_buttonActionPerformed
        // TODO add your handling code here:
        hr_panel.hide();
        ms_update_panel.show();
    }//GEN-LAST:event_go_ms_buttonActionPerformed

    private void ms_empid_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_empid_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ms_empid_tfActionPerformed

    private void ms_ot_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_ot_tfActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ms_ot_tfActionPerformed

    private void bsd_return_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsd_return_buttonActionPerformed
        // TODO add your handling code here:
        bsd_update_panel.hide();
        hr_panel.show();
    }//GEN-LAST:event_bsd_return_buttonActionPerformed

    private void ms_return_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_return_buttonActionPerformed
        // TODO add your handling code here:
        ms_update_panel.hide();
        hr_panel.show();
    }//GEN-LAST:event_ms_return_buttonActionPerformed

    private void ms_confirm_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_confirm_buttonActionPerformed
        // TODO add your handling code here:
        String emp_id = ms_empid_tf.getText();
        Double allowance = Double.parseDouble(ms_allowance_tf.getText());
        Double ot_hrs = Double.parseDouble(ms_ot_tf.getText());
        Double ld = Double.parseDouble(ms_ld_tf.getText());
        Double ad = Double.parseDouble(ms_ad_tf.getText());
        String dr = ms_reason_tf.getText();
        
    }//GEN-LAST:event_ms_confirm_buttonActionPerformed

    private void bsd_confirm_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsd_confirm_buttonActionPerformed
        // TODO add your handling code here:
        String emp_id = bsd_empid_tf.getText();
        Double bs = Double.parseDouble(bsd_bs_tf.getText());
        Double hrs_rt = Double.parseDouble(bsd_hr_tf.getText());
        int wh = Integer.parseInt(bsd_wh_tf.getText());
        
    }//GEN-LAST:event_bsd_confirm_buttonActionPerformed

    private void mrg_view_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrg_view_buttonActionPerformed
        // TODO add your handling code here:
        
        // get the month and year from hr to query
        int yr = Integer.parseInt(mrg_yr_tf.getText());
        String mt = (String)mrg_month_cb.getSelectedItem();
        int monthValue = Client.mapMonthToNumber(mt);
        LocalDate localdate = LocalDate.of(yr,monthValue,1);
        this.hr_selected_date = Date.valueOf(localdate);
        
        checkMonth(localdate);
    }//GEN-LAST:event_mrg_view_buttonActionPerformed

    private void mr_view_back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mr_view_back_buttonActionPerformed
        // TODO add your handling code here:
        monthly_report.hide();
        mrg_panel.show();
    }//GEN-LAST:event_mr_view_back_buttonActionPerformed

    private void view_reason_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_reason_buttonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_view_reason_buttonActionPerformed

    private void go_mr_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go_mr_buttonActionPerformed
        // TODO add your handling code here:
        hr_panel.hide();
        mrg_panel.show();
    }//GEN-LAST:event_go_mr_buttonActionPerformed
    
    private void setSalaryDetails(SalaryDetail sd, SalaryHistory sh, Deduction dd){
        Payroll pr = new Payroll();
        double gross_salary = pr.getGrossSalary(sd.getBase_salary(), sd.getHourly_rate(), sh.getOvertime_hours(), sh.getAllowance());
        
        if(sd.getSd_id() == null){
            salary_name_textfield.setText(Client.getCurrentUser().getName());
            base_salary_textfield.setText("0");
            hourly_rate_textfield.setText("0");
            working_hours_textfield.setText("0");
            allowance_textfield.setText("0");
            overtime_hours_textfield.setText("0");
            gross_salary_textfield.setText("0");
            epf_textfield.setText("0");
            socso_textfield.setText("0");
            eis_textfield.setText("0");
            income_tax_textfield.setText("0");
            leave_deduction_textfield.setText("0");
            additional_deduction_textfield.setText("0");
            net_salary_textfield.setText("0");
        }
        else if(sh.getSHId() == null){
            salary_name_textfield.setText(Client.getCurrentUser().getName());
            base_salary_textfield.setText(String.valueOf(sd.getBase_salary()));
            hourly_rate_textfield.setText(String.valueOf(sd.getHourly_rate()));
            working_hours_textfield.setText(String.valueOf(sd.getWorking_hours()));
            allowance_textfield.setText("0");
            overtime_hours_textfield.setText("0");
            gross_salary_textfield.setText("0");
            epf_textfield.setText("0");
            socso_textfield.setText("0");
            eis_textfield.setText("0");
            income_tax_textfield.setText("0");
            leave_deduction_textfield.setText("0");
            additional_deduction_textfield.setText("0");
            net_salary_textfield.setText("0");
        }
        else{
            salary_name_textfield.setText(Client.getCurrentUser().getName());
            base_salary_textfield.setText(String.valueOf(sd.getBase_salary()));
            hourly_rate_textfield.setText(String.valueOf(sd.getHourly_rate()));
            working_hours_textfield.setText(String.valueOf(sd.getWorking_hours()));
            allowance_textfield.setText(String.valueOf(sh.getAllowance()));
            overtime_hours_textfield.setText(String.valueOf(sh.getOvertime_hours()));
            gross_salary_textfield.setText(String.valueOf(gross_salary));
            epf_textfield.setText(String.valueOf(dd.getTax().getEPF()));
            socso_textfield.setText(String.valueOf(dd.getTax().getSOCSO()));
            eis_textfield.setText(String.valueOf(dd.getTax().getEIS()));
            income_tax_textfield.setText(String.valueOf(dd.getTax().getIncomeTax()));
            leave_deduction_textfield.setText(String.valueOf(dd.getLeave_deduction()));
            additional_deduction_textfield.setText(String.valueOf(dd.getOther_deduction()));
            net_salary_textfield.setText(String.valueOf(pr.getNetSalary(gross_salary, dd.getTotalDeductions(gross_salary))));
        }
    }
    
    private void setPersonalDetail(){
        Employee current_user = Client.getCurrentUser();
        personal_name_textfield.setText(current_user.getName());
        personal_contact_textfield.setText(current_user.getContact_no());
        personal_ic_textfield.setText(current_user.getIc_no());
        personal_department_textfield.setText(current_user.getDepartment());
    }
    
    private String checkMonth(LocalDate localDate){
        
        int year = localDate.getYear();
        int month = localDate.getMonthValue();
        
        LocalDate currentDate = LocalDate.now();
        int currentYear = currentDate.getYear();
        int currentMonth = currentDate.getMonthValue();
        
        LocalDate firstDate = Client.getFirstDate();
        int firstYear = firstDate.getYear();
        int firstMonth = firstDate.getMonthValue();
        
        if (firstDate == null){
            return "null";
        } else {
            if (year <= )
        }
    }
    
    private void setMonthlyReport(LocalDate localDate){
        
        int year = localDate.getYear();
        int month = localDate.getMonthValue();
        
        
        
        
        
        
        
        //mr_date_tf.setText(dateString);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws MalformedURLException, RemoteException, NotBoundException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(payrollGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(payrollGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(payrollGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payrollGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
   
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payrollGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel additional_deduction_label;
    private javax.swing.JTextField additional_deduction_textfield;
    private javax.swing.JLabel allowance_label;
    private javax.swing.JTextField allowance_textfield;
    private javax.swing.JLabel base_salary_label;
    private javax.swing.JTextField base_salary_textfield;
    private javax.swing.JTextField bsd_bs_tf;
    private javax.swing.JButton bsd_confirm_button;
    private javax.swing.JTextField bsd_empid_tf;
    private javax.swing.JTextField bsd_hr_tf;
    private javax.swing.JButton bsd_return_button;
    private javax.swing.JPanel bsd_update_panel;
    private javax.swing.JTextField bsd_wh_tf;
    private javax.swing.JLabel contact_no_label;
    private javax.swing.JLabel department_label;
    private javax.swing.JLabel eis_label;
    private javax.swing.JTextField eis_textfield;
    private javax.swing.JLabel epf_label;
    private javax.swing.JTextField epf_textfield;
    private javax.swing.JButton go_bsd_button;
    private javax.swing.JButton go_mr_button;
    private javax.swing.JButton go_ms_button;
    private javax.swing.JLabel gross_salary_label;
    private javax.swing.JTextField gross_salary_textfield;
    private javax.swing.JLabel hourly_rate_label;
    private javax.swing.JTextField hourly_rate_textfield;
    private javax.swing.JButton hr_back_login_button;
    private javax.swing.JPanel hr_panel;
    private javax.swing.JLabel ic_no_label;
    private javax.swing.JLabel income_tax_label;
    private javax.swing.JTextField income_tax_textfield;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel leave_deduction_label;
    private javax.swing.JTextField leave_deduction_textfield;
    private javax.swing.JComboBox<String> month_combo_box;
    private javax.swing.JPanel monthly_report;
    private javax.swing.JTextField mr_date_tf;
    private javax.swing.JTextField mr_no_emp_tf;
    private javax.swing.JTable mr_tb;
    private javax.swing.JButton mr_view_back_button;
    private javax.swing.JComboBox<String> mrg_month_cb;
    private javax.swing.JPanel mrg_panel;
    private javax.swing.JButton mrg_view_button;
    private javax.swing.JTextField mrg_yr_tf;
    private javax.swing.JTextField ms_ad_tf;
    private javax.swing.JTextField ms_allowance_tf;
    private javax.swing.JButton ms_confirm_button;
    private javax.swing.JTextField ms_empid_tf;
    private javax.swing.JTextField ms_ld_tf;
    private javax.swing.JTextField ms_ot_tf;
    private javax.swing.JTextField ms_reason_tf;
    private javax.swing.JButton ms_return_button;
    private javax.swing.JPanel ms_update_panel;
    private javax.swing.JTextField net_salary_textfield;
    private javax.swing.JLabel nnet_dalary_label;
    private javax.swing.JLabel overtime_hour_label;
    private javax.swing.JTextField overtime_hours_textfield;
    private javax.swing.JButton pd_back_button;
    private javax.swing.JButton pd_salary_button;
    private javax.swing.JTextField personal_contact_textfield;
    private javax.swing.JTextField personal_department_textfield;
    private javax.swing.JLabel personal_details_label;
    private javax.swing.JPanel personal_details_panel;
    private javax.swing.JTextField personal_ic_textfield;
    private javax.swing.JLabel personal_name_label;
    private javax.swing.JTextField personal_name_textfield;
    private javax.swing.JButton salary_back_button;
    private javax.swing.JPanel salary_details_panel;
    private javax.swing.JLabel salary_name_label;
    private javax.swing.JTextField salary_name_textfield;
    private javax.swing.JLabel socso_label;
    private javax.swing.JTextField socso_textfield;
    private javax.swing.JTable total_table;
    private javax.swing.JButton view_reason_button;
    private javax.swing.JLabel working_hours_label;
    private javax.swing.JTextField working_hours_textfield;
    private javax.swing.JComboBox<String> year_combo_box;
    // End of variables declaration//GEN-END:variables
}
